# ==================================================
# 1. Configurações do Servidor
# ==================================================
server.port=8080

# ==================================================
# 2. Configurações do Banco de Dados H2 (Em Memória)
# ==================================================
spring.datasource.url=jdbc:h2:mem:agendamentodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita a interface web do H2 Console (Acesso via navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==================================================
# 3. Configurações do JPA / Hibernate
# ==================================================
# Cria e atualiza as tabelas automaticamente com base nas entidades @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Exibe os comandos SQL executados no console (Ótimo para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desabilita o aviso do Open In View no console
spring.jpa.open-in-view=false

# ==================================================
# 4. Configuração do Swagger / OpenAPI
# ==================================================
# Define o caminho de acesso à documentação do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html